### ISSUE TITLE
Habit Event Card & Adapter

### ISSUE THREAD

**Issue by trnglina** [CMPUT301F21T22/Nabu#10]
- [ ] A child card view of Habit Card (#29), containing:
  - The date
  - An optional comment
  - An optional image
  - An optional location
  - An overflow menu, containing options to:
    - Edit the habit event
    - Remove the habit event
- [ ] An ArrayAdapter<Event> that renders an array of `Event`s with our custom layout

**Comment by wigandt-dot** [comment]
Code complete for habit event card and habit event card adapter.
