### ISSUE TITLE
Comments on Project part 3

### ISSUE THREAD

**Issue by hamzaMAlvi** [CMPUT301F21T22/Nabu#111]
# Comments and marks on project part 3. Please make issues with respect to comments if needed and link them with this issue.
Do not repeat the same mistakes again, noted by your TA during the meetings. Ask questions as early as possible. Use this issue for asking questions regarding comments etc.

****

### Comment: 
Excellent quality of the app, it looks professional and the calender view in navigation bar looks neat. I liked how the navigation slider is at the bottom which makes the sliding from one screen to another smooth. The team has covered half of the requirements. Just a few improvements can be to make sure register and login button is in the login page instead of directly asking the email. Also once the user has created/edited any habit after saving redirect them back to home screen.

- [x] #112
- [x] #113

### Comment:
Good job in arranging the files according to specific folders. It will help in better understanding the porject once it grows big and complex. Just one improvement will be to maintain a uniform commenting pattern on top of every class. It can help third party developers to better understand the purpose of the specific class.

- [x] #114

### Comment:
You should be more elaborate more on the user stories, e.g. Acceptance criteria? The way you have it is just stating the user story.

- [x] #115

### Comment:
A majority of the intent tests fail or seem to hang, they should not fail. They seem to be stuck on the screen waiting for the first + last name to be entered. Lack of unit tests for entity (model) classes. You have a lot of empty test files with only the setup.

- [x] #116
- [x] #89 

### Comment:
Hard to read. All UML is supposed to be in a single picture. Please fix this ASAP! 

- [x] #117

### Comment:
All comments were addressed, issues were created for comments and were tracked.

### Comment:
Nice work, improvements are needed for the final demo, I pointed most of the things during the demo. Make them reflect on UI mockups and storyboards.

- [x] #91 
- [x] #118

### Comment:
There is some kind of sprint planning. They displays the understanding of scrum. Sprints are not planned by user stories, no priority planning in addressing user stories, No review of sprint shown. user stories are somewhat completed.

### Comment:
Comments and suggestions given on the spot should not be repeated. The organization of presented features should be improved. Prepare well before the demo time, and practice again and again.

- [x] #119

### Comment:
Good Work. Need some improvements in following the standards of tools.

### Comment:
Well above average relative quality, overall comprehensiveness, creativity, attractiveness, and innovation

**Comment by 4ry4nm4lik** [comment]
Question regarding the demo - Do we need just a video presenting the application with the group members speaking in the background or does the group have to be actively presenting the application live?
