### ISSUE TITLE
Habit Card & Adapter

### ISSUE THREAD

**Issue by trnglina** [CMPUT301F21T22/Nabu#29]
- [x] A card view, containing:
  - Habit title
  - Habit reason
  - Habit start date
  - Habit occurrence
  - An overflow menu, containing options to:
    - View habit events associated with the habit
    - Edit the habit
    - Remove the habit
- [x] An ArrayAdapter<Habit> that renders an array of `Habit`s with our custom layout

---

Resolves the following user stories:

- **US 01.08.01** (size: 2, risk: low)
    As a doer, I want to see a list of all my habits.

**Comment by wigandt-dot** [comment]
Layout for each card and the adapter to construct them is complete.
