### ISSUE TITLE
Comments on the Part 2 Submission

### ISSUE THREAD

**Issue by hamzaMAlvi** [CMPUT301F21T22/Nabu#63]
These are the comments by other TA's on the project part 2 submission. You need to address these comments for your next submission.
If necessary make new issues relevant to the comments and link them to this issue (make them a subtask of this issue). If you have any confusion mention me in the comments section of this issue along with the question.

@trnglina @4ry4nm4lik @joshvuong @wigandt-dot @LoveMia0 

- Good job in maintaining multiple dashboards for different deliverables, one thing missing in all the dashboards is the risk level assessment , elaborate description of the user stories, and halfway checkpoints.
  - [x] #65

- For presentation, wrong CRC cards format. Responsibilities should be clearly defined e.g. "Habit Event List" cant add an event rather it should be a separate class like HabitUtility or HabitEventUtility/Controller/Manager etc. Classes related to Followers/Following user scenarios are missing. Database handling classes are missing.
  - [x] #64

- UI mockups are consistent and look professional but they are not linked with each other. Link them through actions by the user.

- Good Job in using GitHub. Follow the standard practices for using different tools. Make sure everyone contributes to the project.

**Comment by trnglina** [comment]
With regards to point 3:
> UI mockups are consistent and look professional but they are not linked with each other. Link them through actions by the user.

I believe user actions are modeled in the [Storyboard](https://github.com/CMPUT301F21T22/Nabu/blob/main/design/Storyboard.pdf), which was complete before Part 2. Is there anything we're missing as part of our storyboards, or is this something different, and if so, in what ways?

**Comment by hamzaMAlvi** [comment]
> 
> 
> @hamzaMAlvi With regards to point 3:
> 
> > UI mockups are consistent and look professional but they are not linked with each other. Link them through actions by the user.
> 
> I believe user actions are modeled in the [Storyboard](https://github.com/CMPUT301F21T22/Nabu/blob/main/design/Storyboard.pdf), which was complete before Part 2. Is there anything we're missing as part of our storyboards, or is this something different, and if so, in what ways?

There is nothing missing. I have talked to the TA, who marked this part. He missed it and has rechecked it (no further comments).

**Comment by hamzaMAlvi** [comment]
@trnglina @4ry4nm4lik @joshvuong @wigandt-dot @LoveMia0 

Marks
Product Backlog: 2/3
OO Analysis: 2/3
UI MockUp & Storyboard: 3/3
Tool Practices: 1/1

**Comment by wigandt-dot** [comment]
Finished updating the social related CRC cards.
