### ISSUE TITLE
Testing testDebugUnitTest error

### ISSUE THREAD

**Issue by wigandt-dot** [CMPUT301F21T22/Nabu#79]
I have been creating the tests when I noticed whenever I try to run them, that the following error comes up:

> Task :app:compileDebugUnitTestJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:processDebugUnitTestJavaRes NO-SOURCE
> Task :app:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.
> There were failing tests. See the report at: file:///C:/Users/nethp/Documents/Nabu/Nabu/src/app/build/reports/tests/testDebugUnitTest/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 5s
21 actionable tasks: 3 executed, 18 up-to-date
1:13:36 a.m.: Tasks execution finished ':app:cleanTestDebugUnitTest :app:testDebugUnitTest --tests "ca.cmput301f21t22.nabu.EventChronologicalComparatorTest"'.

Even on tests without the depreciated code (Date(year, month, day)), the error still seems to trigger. The tests are currently up to date in my branch, and I'll continue to create and upload them, but eventually will need help just figuring out why this error shows up.

**Comment by trnglina** [comment]
Yeah, so I think this is the crucial point:
> There were failing tests. See the report...

That reads to me like some of the tests are failing, so either the tests are wrong, expecting behaviour that isn't correct, or there's a bug in the code being tested.

If you look carefully, there should be windows in Android Studio telling you which tests failed. Looking at the Test History might also help. That might tell you whether it's the tests that are incorrect, or the code. If it's the code, you should file a separate issue for those bugs.

![image](https://user-images.githubusercontent.com/19496781/140323238-01135adb-43a4-459f-9aee-3736c30ebb82.png)
