### ISSUE TITLE
Habits Fragment

### ISSUE THREAD

**Issue by trnglina** [CMPUT301F21T22/Nabu#8]
A list of Habit Cards (#29), allowing the adding of new habits and the reordering of existing habits.

- [x] #33
- [x] #34

---

Resolves the following user stories:

- **US 01.01.01** (size: 3, risk: medium)
   As a doer, I want to add a habit, giving it a brief title, reason, date to start, and whether it is public or private.
- **US 01.03.01** (size: 2, risk: low)
As a doer, I want to view a given habit and its details.
- ** US 01.05.01** (size: 1, risk: low)
As a doer, I want to delete a habit of mine, and any corresponding habit events.

**Comment by wigandt-dot** [comment]
Completed Habits Fragment code and layout
